version: 0.2



phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-south-1 )
      - REPOSITORY_URI=065014346317.dkr.ecr.ap-south-1.amazonaws.com/project-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo build started on `date`
      - echo building the docker image.....
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker images
      - echo Writing image definitions file...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"userContainer","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: 
         - '**/*'  
         - imagedefinitions.json
